insert into autor values (1, 'Alex Gill');
insert into autor values (2, 'Amanda Marshall');
insert into autor values (3, 'Ami Onuki');
insert into autor values (4, 'Alex Band');
insert into autor values (5, 'Tim Bendzko');
insert into autor values (6, 'Big Nelo');
insert into autor values (7, 'Bruno Branco');
insert into autor values (8, 'Enrique Bunbury');
insert into autor values (9, 'Nick Carter');
insert into autor values (10, 'Danni Carlos');
insert into autor values (11, 'Ewa Farna');
insert into autor values (12, 'Fiuk');
insert into autor values (13, 'Alejandro Fuentes');
insert into autor values (14, 'Alex Goot');
insert into autor values (15, 'Gotye');
insert into autor values (16, 'Daryl Hall');
insert into autor values (17, 'Hélvio Sodré');
insert into autor values (18, 'Chlöe Howl');
insert into autor values (19, 'Duncan James');
insert into autor values (20, 'Piret Järvis');
insert into autor values (21, 'Kelly Osbourne');
insert into autor values (22, 'Triinu Kivilaan');
insert into autor values (23, 'Lenna Kuurmaa');
insert into autor values (24, 'Nick Lachey');
insert into autor values (25, 'Avril Lavigne');
insert into autor values (26, 'Letícia Navas');
insert into autor values (27, 'Liah');
insert into autor values (28, 'Lulu Santos');
insert into autor values (29, 'Marcus Menna');
insert into autor values (30, 'Marisa Liz');
insert into autor values (31, 'Matt Cardle');
insert into autor values (32, 'Casey McPherson');
insert into autor values (33, 'Megh Stock');
insert into autor values (34, 'Alyson Michalka');
insert into autor values (35, 'Amanda Michalka');
insert into autor values (36, 'Bea Miller');
insert into autor values (37, 'Alanis Morissette');
insert into autor values (38, 'Kjetil Mørland');
insert into autor values (39, 'Stevie Nicks');
insert into autor values (40, 'Ovelha (cantor)');
insert into autor values (41, 'Pali (cantor)');
insert into autor values (42, 'Paul Engemann');
insert into autor values (43, 'Paul G');
insert into autor values (44, 'Katy Perry');
insert into autor values (45, 'Pip (cantor)');
insert into autor values (46, 'Rocky Lynch');
insert into autor values (47, 'Susanna Hoffs');
insert into autor values (48, 'Ryan Tedder');
insert into autor values (49, 'Teru');
insert into autor values (50, 'Tomomi Kahala');
insert into autor values (51, 'Tsunku');
insert into autor values (52, 'Robbie Williams');
insert into autor values (53, 'Yndia');
insert into autor values (54, 'Paul Young');
insert into autor values (55, 'Yumi Yoshimura');
insert into autor values (56, 'Zuzana Smatanová');
insert into autor values (57, 'Ahn Sojin');
insert into autor values (58, 'Ailee');
insert into autor values (59, 'Baby Soul');
insert into autor values (60, 'Bada (cantora)');
insert into autor values (61, 'Bae Sung-yeon');
insert into autor values (62, 'Baek A-yeon');
insert into autor values (63, 'BamBam');
insert into autor values (64, 'Bona (artista)');
insert into autor values (65, 'Max Changmin');
insert into autor values (66, 'Cho Hye-yeon');
insert into autor values (67, 'Cho Hyun-young');
insert into autor values (68, 'Cho Seung-hee');
insert into autor values (69, 'Dana (cantora sul-coreana)');
insert into autor values (70, 'David Oh');
insert into autor values (71, 'Dean (cantor)');
insert into autor values (72, 'E-Young');
insert into autor values (73, 'Eddy Kim');
insert into autor values (74, 'Kim Eli');
insert into autor values (75, 'Elkie (artista)');
insert into autor values (76, 'Eric Nam');
insert into autor values (77, 'G.NA');
insert into autor values (78, 'Go Eun-bi');
insert into autor values (79, 'Haeryung');
insert into autor values (80, 'Han Hye-ri');
insert into autor values (81, 'Han Sun-hwa');
insert into autor values (82, 'Heejin');
insert into autor values (83, 'Henry Lau');
insert into autor values (84, 'Heo Ga-yoon');
insert into autor values (85, 'Hong Yoo-kyung');
insert into autor values (86, 'Nichkhun');
insert into autor values (87, 'Hoya (artista)');
insert into autor values (88, 'Hwang Min-hyun');
insert into autor values (89, 'Hwasa');
insert into autor values (90, 'Hyun Seung-hee');
insert into autor values (91, 'Hyunjin');
insert into autor values (92, 'IU (artista)');
insert into autor values (93, 'J-Min');
insert into autor values (94, 'Jackson Wang');
insert into autor values (95, 'Kim Jae-joong');
insert into autor values (96, 'Jang Hyun-seung');
insert into autor values (97, 'JeA');
insert into autor values (98, 'Jeon So-mi');
insert into autor values (99, 'Jeon So-yeon');
insert into autor values (100, 'Jiyul Yang');
insert into autor values (101, 'Jo So-jin');
insert into autor values (102, 'Moon Jong-up');
insert into autor values (103, 'Jun Hyoseong');
insert into autor values (104, 'Jung Dae-hyun');
insert into autor values (105, 'Jung Eun-woo');
insert into autor values (106, 'Uhm Jung-hwa');
insert into autor values (107, 'Jung Jin-young');
insert into autor values (108, 'Jung Eun-ji');
insert into autor values (109, 'Jung Hana');
insert into autor values (110, 'Jung Yong-hwa');
insert into autor values (111, 'Juniel');
insert into autor values (112, 'Kahi');
insert into autor values (113, 'Kan Mi-youn');
insert into autor values (114, 'Kang Daniel');
insert into autor values (115, 'Kang Seung-yoon');
insert into autor values (116, 'Kangta');
insert into autor values (117, 'Kei (artista)');
insert into autor values (118, 'Ki Hui-hyeon');
insert into autor values (119, 'Kihyun');
insert into autor values (120, 'Kim Chung-ha');
insert into autor values (121, 'Kim Da-som');
insert into autor values (122, 'Kim Dong-wan');
insert into autor values (123, 'Kim Hyo-yeon');
insert into autor values (124, 'Kim Jong-kook');
insert into autor values (125, 'Kim Jung-woo');
insert into autor values (126, 'Kim Na-young');
insert into autor values (127, 'Kim So-hee (1995)');
insert into autor values (128, 'Kim So-hee (1999)');
insert into autor values (129, 'Kim So-hye');
insert into autor values (130, 'Kim Ye-won (artista)');
insert into autor values (131, 'Kim Chan-mi');
insert into autor values (132, 'Kim Jung-ah');
insert into autor values (133, 'Kim Seol-hyun');
insert into autor values (134, 'Koo Jun-hoe');
insert into autor values (135, 'Kwon So-hyun');
insert into autor values (136, 'BoA');
insert into autor values (137, 'Kwon Min-ah');
insert into autor values (138, 'Kwon Na-ra');
insert into autor values (139, 'Kwon Ri-se');
insert into autor values (140, 'Kyla Massie');
insert into autor values (141, 'Lee Gi-kwang');
insert into autor values (142, 'Lee Hae-in');
insert into autor values (143, 'Lee Hae-ri');
insert into autor values (144, 'Lee Joon');
insert into autor values (145, 'Lee Seung-hwan');
insert into autor values (146, 'Lee So-jung');
insert into autor values (147, 'Lee Su-hyun');
insert into autor values (148, 'Lee Sung-yeol');
insert into autor values (149, 'Lee Hi');
insert into autor values (150, 'Lee Hyori');
insert into autor values (151, 'Lee Kiseop');
insert into autor values (152, 'Leeteuk');
insert into autor values (153, 'Lim Na-young');
insert into autor values (154, 'Loco (rapper)');
insert into autor values (155, 'Kang Mi-na');
insert into autor values (156, 'Moonbyul');
insert into autor values (157, 'Son Ji-hyun');
insert into autor values (158, 'Namjoo');
insert into autor values (159, 'Nana (artista)');
insert into autor values (160, 'Narsha');
insert into autor values (161, 'NC.A');
insert into autor values (162, 'Lista de membros de NCT');
insert into autor values (163, 'NS Yoon-G');
insert into autor values (164, 'Oh Ha-young');
insert into autor values (165, 'Park Hyo-shin');
insert into autor values (166, 'Park Ji-hoon');
insert into autor values (167, 'Park Jin-young');
insert into autor values (168, 'Park Jung-ah');
insert into autor values (169, 'Park Si-yeon');
insert into autor values (170, 'Park Yoo-chun');
insert into autor values (171, 'Park Cho-rong');
insert into autor values (172, 'Park Cho-ah');
insert into autor values (173, 'Jay Park');
insert into autor values (174, 'Qri');
insert into autor values (175, 'Raina (artista)');
insert into autor values (176, 'Rena (cantora)');
insert into autor values (177, 'Roa (cantora)');
insert into autor values (178, 'Ryu Hyo-young');
insert into autor values (179, 'Kim Se-jeong');
insert into autor values (180, 'Seo Eun-kwang');
insert into autor values (181, 'Seo Yu-na');
insert into autor values (182, 'Shannon Williams');
insert into autor values (183, 'Shin Jong-kook');
insert into autor values (184, 'Shin Soo-hyun');
insert into autor values (185, 'Shin Hye-jeong');
insert into autor values (186, 'Shoo (cantora)');
insert into autor values (187, 'SinB');
insert into autor values (188, 'Solar (cantora)');
insert into autor values (189, 'Son Dong-woon');
insert into autor values (190, 'Son Dam-bi');
insert into autor values (191, 'Son Na-eun');
insert into autor values (192, 'Song Min-ho');
insert into autor values (193, 'Song Jieun');
insert into autor values (194, 'Sorn (artista)');
insert into autor values (195, 'Sowon');
insert into autor values (196, 'Tablo');
insert into autor values (197, 'Thunder (cantor)');
insert into autor values (198, 'Umji');
insert into autor values (199, 'Wheein');
insert into autor values (200, 'Xiah Junsu');
insert into autor values (201, 'Yehana');
insert into autor values (202, 'Yerin');
insert into autor values (203, 'Yong Jun-hyung');
insert into autor values (204, 'Yoo Yeon-jung');
insert into autor values (205, 'Yoo Young-jae');
insert into autor values (206, 'Yoo Ah-ra');
insert into autor values (207, 'Yoo Ji-ae');
insert into autor values (208, 'Yoon Chae-kyung');
insert into autor values (209, 'Yoon Doo-joon');
insert into autor values (210, 'Yoon Bo-mi');
insert into autor values (211, 'Youngjae');
insert into autor values (212, 'Yuha');
insert into autor values (213, 'Yunho');
