package cesium;

import java.util.*;
import java.util.HashMap;
import java.awt.FlowLayout;
import javax.swing.DefaultListModel;
import javax.swing.ImageIcon;
import javax.swing.JFrame;

/**
 *
 * @author Francisco Oliveira
 * @author Raul Vilas Boas
 * @author Vitor Peixoto
 */
public class Cesium extends JFrame implements Observer {
    private Associacao associacao;
    DefaultListModel<Integer> model = new DefaultListModel<>();
    //Database data = new Database();
    
    public Cesium() {
        this.setLayout(new FlowLayout());
        this.pack();
        this.setVisible(true);
        initComponents();
        this.setTitle("CESIUM");
        this.setLocationRelativeTo(null);
        ImageIcon icon = new ImageIcon(getClass().getClassLoader().getResource("resources/cesium.png"));
        cesiumLogo.setIcon(icon);
        
        // inicializaçao
        HashMap<Integer,Boolean> quota1 = new HashMap<Integer,Boolean>();
        HashMap<Integer,Boolean> quota2 = new HashMap<Integer,Boolean>();
        HashMap<Integer,Boolean> quota3 = new HashMap<Integer,Boolean>();
        HashMap<Integer,Boolean> quota4 = new HashMap<Integer,Boolean>();
        HashMap<Integer,Boolean> quota5 = new HashMap<Integer,Boolean>();
        HashMap<Integer,Boolean> quota6 = new HashMap<Integer,Boolean>();
        quota1.put(2015,true);quota1.put(2016,true);quota1.put(2017,true);
        quota2.put(2016,true);quota2.put(2017,false);
        quota3.put(2015,true);quota3.put(2016,true);quota3.put(2017,false);
        quota4.put(2017,true);
        quota5.put(2016,true);quota5.put(2017,false);
        quota6.put(2013,true);quota6.put(2014,true);quota6.put(2015,true);quota6.put(2016,true);quota6.put(2017,true);
        Socio socio1 = new Socio(79175,"Vitor Peixoto","Eng. Informática",3,"Avenida das Tulipas, 193, 1º esq.",2015,quota1);
        Socio socio2 = new Socio(79617,"Raul Vilas Boas","Eng. Informática",3,"Rua de San Junipero, 21",2016,quota2);
        Socio socio3 = new Socio(78416,"Francisco Oliveira","Eng. Informática",3,"Avenida Central, 90",2015,quota3);
        Socio socio4 = new Socio(79814,"Ana Ribeiro","Ciências da Computação",1,"Rua 1º de Maio, 112",2017,quota4);
        Socio socio5 = new Socio(78711,"António Carvalho","Eng. Civil",2,"Avenida do Cruzeiro, 96",2016,quota5);
        Socio socio6 = new Socio(76125,"Bruno Esteves","Eng. Informática",5,"Avenida das Antas",2013,quota6);

        this.associacao = new Associacao();
        this.associacao.addObserver(this);
        associacao.addSocio(socio1);
        associacao.addSocio(socio2);
        associacao.addSocio(socio3);
        associacao.addSocio(socio4);
        associacao.addSocio(socio5);
        associacao.addSocio(socio6);
        idList.setSelectedIndex(0);
    }
    
    public void update(Observable o, Object arg){
        Set<Integer> keys = this.associacao.getKeySet();
        for(Integer k : keys){
            if( !model.contains(k) ) this.model.addElement(k);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        idList = new javax.swing.JList<>();
        jLabel3 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        nomeField = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        cursoField = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        novoButton = new javax.swing.JButton();
        sairButton = new javax.swing.JButton();
        quotasButton = new javax.swing.JButton();
        moradaField = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        anoField = new javax.swing.JFormattedTextField();
        cesiumLogo = new javax.swing.JLabel();

        jLabel1.setText("jLabel1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(255, 255, 255));
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        setResizable(false);

        jScrollPane1.setBackground(new java.awt.Color(255, 255, 255));

        idList.setModel(model);
        idList.setName(""); // NOI18N
        idList.addListSelectionListener(new javax.swing.event.ListSelectionListener() {
            public void valueChanged(javax.swing.event.ListSelectionEvent evt) {
                idListValueChanged(evt);
            }
        });
        jScrollPane1.setViewportView(idList);

        jLabel5.setLabelFor(idList);
        jLabel5.setText("ID Sócio:");

        nomeField.setEditable(false);

        jLabel6.setLabelFor(idList);
        jLabel6.setText("Nome:");

        cursoField.setEditable(false);

        jLabel7.setLabelFor(idList);
        jLabel7.setText("Curso:");

        jLabel8.setLabelFor(idList);
        jLabel8.setText("Ano:");

        novoButton.setText("Novo");
        novoButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                novoButtonActionPerformed(evt);
            }
        });

        sairButton.setText("Sair");
        sairButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sairButtonActionPerformed(evt);
            }
        });

        quotasButton.setText("Quotas");
        quotasButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                quotasButtonActionPerformed(evt);
            }
        });

        moradaField.setEditable(false);

        jLabel9.setLabelFor(idList);
        jLabel9.setText("Morada:");

        anoField.setEditable(false);

        cesiumLogo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        cesiumLogo.setText(" ");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel3)
                    .addComponent(jLabel5)))
            .addGroup(layout.createSequentialGroup()
                .addGap(81, 81, 81)
                .addComponent(cesiumLogo))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 127, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(jLabel6, javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(jLabel7)
                                    .addGap(0, 159, Short.MAX_VALUE))
                                .addComponent(cursoField))
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                            .addComponent(jLabel8)
                            .addGap(18, 18, 18))
                        .addComponent(jLabel9, javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(nomeField, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 234, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(anoField, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(moradaField, javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                .addComponent(novoButton, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(quotasButton, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(sairButton, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE))))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(cesiumLogo)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(jLabel6))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(nomeField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel7)
                            .addComponent(jLabel8))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(cursoField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(anoField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel9)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(moradaField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(novoButton, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(quotasButton, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(sairButton, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 196, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(0, 44, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void novoButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_novoButtonActionPerformed
        NovoSocio form = new NovoSocio(associacao);
        form.pack();
        form.setVisible(true);
    }//GEN-LAST:event_novoButtonActionPerformed

    private void quotasButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_quotasButtonActionPerformed
        Quotas quotas = new Quotas( associacao.getSocio(idList.getSelectedValue()) );
        quotas.pack();
        quotas.setVisible(true);
    }//GEN-LAST:event_quotasButtonActionPerformed

    private void idListValueChanged(javax.swing.event.ListSelectionEvent evt) {//GEN-FIRST:event_idListValueChanged
        nomeField.setText(associacao.getSocio(idList.getSelectedValue()).getNome() );
        cursoField.setText(associacao.getSocio(idList.getSelectedValue()).getCurso() );
        anoField.setText(Integer.toString(associacao.getSocio(idList.getSelectedValue()).getAno()) );
        moradaField.setText(associacao.getSocio(idList.getSelectedValue()).getMorada() );
    }//GEN-LAST:event_idListValueChanged

    private void sairButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sairButtonActionPerformed
        System.exit(0);
    }//GEN-LAST:event_sairButtonActionPerformed

    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Cesium.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Cesium.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Cesium.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Cesium.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Cesium().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JFormattedTextField anoField;
    private javax.swing.JLabel cesiumLogo;
    private javax.swing.JTextField cursoField;
    private javax.swing.JList<Integer> idList;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField moradaField;
    private javax.swing.JTextField nomeField;
    private javax.swing.JButton novoButton;
    private javax.swing.JButton quotasButton;
    private javax.swing.JButton sairButton;
    // End of variables declaration//GEN-END:variables
}
