package cesium;

import java.awt.FlowLayout;
import java.awt.Image;
import java.util.Calendar;
import java.util.HashMap;
import java.util.Map;
import javax.swing.ImageIcon;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.JScrollPane;
import javax.swing.JTable;
import javax.swing.event.TableModelListener;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableModel;

/**
 *
 * @author Francisco Oliveira
 * @author Raul Vilas Boas
 * @author Vitor Peixoto
 */
public class Quotas extends javax.swing.JFrame {
    Socio socio;
    HashMap<Integer,Boolean> quotas;
    DefaultTableModel model;
    
    public Quotas(){
        socio = new Socio();
        initComponents();
        this.setTitle("Quotas Sócio");
        this.setLocationRelativeTo(null);

    }
    public Quotas(Socio s) {
        socio = s;
        quotas = socio.getQuotas();
        
        String[] colunas = {"Ano", "Pago"};
        Object[][] data = new Object[quotas.keySet().size()][2];
        int i=0;
        for (Integer ano : quotas.keySet()){
            Boolean pago = quotas.get(ano);
            data[i][0] = ano;
            if(pago) data[i][1] = "Pago";
            else data[i][1] = "Não Pago";
            i++;
        }
        model = new DefaultTableModel(data,colunas);
        
        initComponents();
        this.setTitle("Quotas Sócio");
        this.setLocationRelativeTo(null);
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        pagarButton = new javax.swing.JButton();

        jTable1.setModel(model);
        jTable1.setEnabled(false);
        jScrollPane1.setViewportView(jTable1);

        pagarButton.setText("Pagar Quota");
        pagarButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pagarButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 375, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(145, 145, 145)
                        .addComponent(pagarButton, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 175, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(pagarButton, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void pagarButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pagarButtonActionPerformed
        if(!quotas.get(Calendar.getInstance().get(Calendar.YEAR))){
            quotas.replace(Calendar.getInstance().get(Calendar.YEAR), true);
            JOptionPane.showMessageDialog(null, "Pagamento de 5€ confirmado!", "Quota paga", JOptionPane.INFORMATION_MESSAGE);
            Quotas.this.setVisible(false);
        }
        else{
           
            ImageIcon icon = new ImageIcon(getClass().getClassLoader().getResource("resources/aviso.png"));
            JOptionPane.showMessageDialog(null, "O sócio já tem as quotas em dia!", "Aviso", JOptionPane.INFORMATION_MESSAGE, icon);
        }
    }//GEN-LAST:event_pagarButtonActionPerformed

    public static void main(String args[]) {
        
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Quotas().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JButton pagarButton;
    // End of variables declaration//GEN-END:variables
    

}
