package horarios.presentation;

/**
 *
 * @author Francisco Oliveira
 * @author Raul Vilas Boas
 * @author Vitor Peixoto
 */
import horarios.business.*;
import java.awt.Color;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.ImageIcon;
import javax.swing.JFrame;
import javax.swing.JOptionPane;

public class FormDocente extends javax.swing.JFrame {
    private Facade facade;
    private final JFrame formPai;
    
    
    public FormDocente(Facade facade, JFrame formPai) {
        initComponents();
        this.facade = facade;
        this.formPai = formPai;
        this.setLocationRelativeTo(null);
        this.setDefaultCloseOperation(0);
        refreshComboUC();
        fases();
    }
    
    private void fases(){
        int fase = facade.getDocenteDAO().getFase();
        if(fase==1){
            tabDocente.setEnabledAt(0, false);
            tabDocente.setBackgroundAt(0, Color.gray);
            tabDocente.setForegroundAt(0, Color.darkGray);
            tabDocente.setSelectedIndex(1);
            buttonDirUC.setEnabled(false);
        }
        if(fase==2){
            tabDocente.setEnabledAt(0, false);
            tabDocente.setBackgroundAt(0, Color.gray);
            tabDocente.setForegroundAt(0, Color.darkGray);
            tabDocente.setSelectedIndex(1);
            buttonDirUC.setEnabled(true);
        }
    }

    private void refreshComboUC() { 
        for(UC c : facade.getUCDAO().values()) {
            comboCodAD.addItem(Integer.toString(c.getUC()));
        }
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        tabDocente = new javax.swing.JTabbedPane();
        panelADoc = new javax.swing.JPanel();
        jLabel34 = new javax.swing.JLabel();
        jLabel36 = new javax.swing.JLabel();
        comboTurnoAD = new javax.swing.JComboBox<>();
        jLabel35 = new javax.swing.JLabel();
        comboAlunoAD = new javax.swing.JComboBox<>();
        jLabel37 = new javax.swing.JLabel();
        buttonPresenteAD = new javax.swing.JButton();
        buttonFaltouAD = new javax.swing.JButton();
        comboCodAD = new javax.swing.JComboBox<>();
        textNumAulas = new javax.swing.JTextField();
        jLabel38 = new javax.swing.JLabel();
        panelADir = new javax.swing.JPanel();
        buttonDirCurso = new javax.swing.JButton();
        buttonDirUC = new javax.swing.JButton();
        buttonLogout = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel34.setFont(new java.awt.Font("Lucida Grande", 0, 10)); // NOI18N
        jLabel34.setText("UC");

        jLabel36.setFont(new java.awt.Font("Lucida Grande", 0, 10)); // NOI18N
        jLabel36.setText("Selecionar número dos alunos do turno e clicar no botão respetivo:");

        comboTurnoAD.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                comboTurnoADFocusLost(evt);
            }
        });

        jLabel35.setFont(new java.awt.Font("Lucida Grande", 0, 10)); // NOI18N
        jLabel35.setText("Turno");

        jLabel37.setFont(new java.awt.Font("Lucida Grande", 0, 10)); // NOI18N
        jLabel37.setText("ID Aluno");

        buttonPresenteAD.setText("Presente");
        buttonPresenteAD.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonPresenteADActionPerformed(evt);
            }
        });

        buttonFaltouAD.setText("Faltou");
        buttonFaltouAD.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonFaltouADActionPerformed(evt);
            }
        });

        comboCodAD.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                comboCodADActionPerformed(evt);
            }
        });

        textNumAulas.setEditable(false);
        textNumAulas.setFont(new java.awt.Font("Lucida Grande", 0, 18)); // NOI18N
        textNumAulas.setFocusable(false);
        textNumAulas.setRequestFocusEnabled(false);

        jLabel38.setFont(new java.awt.Font("Lucida Grande", 0, 10)); // NOI18N
        jLabel38.setText("Nº aulas lec.");

        javax.swing.GroupLayout panelADocLayout = new javax.swing.GroupLayout(panelADoc);
        panelADoc.setLayout(panelADocLayout);
        panelADocLayout.setHorizontalGroup(
            panelADocLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelADocLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelADocLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelADocLayout.createSequentialGroup()
                        .addGroup(panelADocLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel36)
                            .addGroup(panelADocLayout.createSequentialGroup()
                                .addComponent(comboAlunoAD, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(buttonPresenteAD, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(buttonFaltouAD, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jLabel37))
                        .addContainerGap(43, Short.MAX_VALUE))
                    .addGroup(panelADocLayout.createSequentialGroup()
                        .addGroup(panelADocLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(panelADocLayout.createSequentialGroup()
                                .addComponent(jLabel34)
                                .addGap(126, 126, 126))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelADocLayout.createSequentialGroup()
                                .addComponent(comboCodAD, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)))
                        .addGroup(panelADocLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel35)
                            .addComponent(comboTurnoAD, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(panelADocLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(textNumAulas, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel38))
                        .addGap(19, 19, 19))))
        );
        panelADocLayout.setVerticalGroup(
            panelADocLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelADocLayout.createSequentialGroup()
                .addGroup(panelADocLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addGroup(panelADocLayout.createSequentialGroup()
                        .addGap(16, 16, 16)
                        .addGroup(panelADocLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel34)
                            .addComponent(jLabel35))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(panelADocLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(comboTurnoAD, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(comboCodAD, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(panelADocLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel38)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(textNumAulas, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel36)
                .addGap(12, 12, 12)
                .addComponent(jLabel37)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panelADocLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(comboAlunoAD, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(buttonPresenteAD)
                    .addComponent(buttonFaltouAD))
                .addContainerGap(14, Short.MAX_VALUE))
        );

        tabDocente.addTab("Registo de faltas", panelADoc);

        buttonDirCurso.setText("Direção Curso");
        buttonDirCurso.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonDirCursoActionPerformed(evt);
            }
        });

        buttonDirUC.setText("Direção UC");
        buttonDirUC.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonDirUCActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout panelADirLayout = new javax.swing.GroupLayout(panelADir);
        panelADir.setLayout(panelADirLayout);
        panelADirLayout.setHorizontalGroup(
            panelADirLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelADirLayout.createSequentialGroup()
                .addGap(142, 142, 142)
                .addGroup(panelADirLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(buttonDirCurso, javax.swing.GroupLayout.PREFERRED_SIZE, 132, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(buttonDirUC, javax.swing.GroupLayout.PREFERRED_SIZE, 132, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(143, Short.MAX_VALUE))
        );
        panelADirLayout.setVerticalGroup(
            panelADirLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelADirLayout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addComponent(buttonDirCurso, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(buttonDirUC, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(36, Short.MAX_VALUE))
        );

        tabDocente.addTab("Área direção", panelADir);

        buttonLogout.setText("Logout");
        buttonLogout.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonLogoutActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(tabDocente)
            .addGroup(layout.createSequentialGroup()
                .addGap(172, 172, 172)
                .addComponent(buttonLogout)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(tabDocente, javax.swing.GroupLayout.PREFERRED_SIZE, 210, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(buttonLogout)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
    
    private void buttonDirCursoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonDirCursoActionPerformed
        if(facade.getSessao().getEstatuto().equals("Diretor Curso")){
            FormDirecaoCurso form = new FormDirecaoCurso(facade,this);
            form.setVisible(true);
        }else{
            ImageIcon icon = new ImageIcon(getClass().getClassLoader().getResource("resources/forbidden.png"));
            JOptionPane.showMessageDialog(null, "Apenas os diretores de curso podem aceder esta área!", "Área interdita", JOptionPane.INFORMATION_MESSAGE, icon);
        }
        
    }//GEN-LAST:event_buttonDirCursoActionPerformed

    private void buttonDirUCActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonDirUCActionPerformed
         if(facade.getSessao().getEstatuto().equals("Diretor UC")){
            FormDirecaoUC form = new FormDirecaoUC(facade,this);
            form.setVisible(true);
        }else{
            ImageIcon icon = new ImageIcon(getClass().getClassLoader().getResource("resources/forbidden.png"));
            JOptionPane.showMessageDialog(null, "Apenas os diretores de UC podem aceder esta área!", "Área interdita", JOptionPane.INFORMATION_MESSAGE, icon);
        }
    }//GEN-LAST:event_buttonDirUCActionPerformed

    private void comboCodADActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_comboCodADActionPerformed
        int codUC = Integer.parseInt(comboCodAD.getSelectedItem().toString());
        comboTurnoAD.removeAllItems();
        for(Turno t : facade.getTurnoDAO().turnosDaUC(codUC)) {
            comboTurnoAD.addItem(Integer.toString(t.getTurno()));
        }
    }//GEN-LAST:event_comboCodADActionPerformed

    private void comboTurnoADFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_comboTurnoADFocusLost
        int numTurno = Integer.parseInt(comboTurnoAD.getSelectedItem().toString());
        comboAlunoAD.removeAllItems();
        textNumAulas.setText(Integer.toString(facade.getRegistoDAO().getNumAulas(numTurno)));
        for(Integer a : facade.getRegistoDAO().alunosInscritosTurno(numTurno)) {
            comboAlunoAD.addItem(Integer.toString(a));
        }
    }//GEN-LAST:event_comboTurnoADFocusLost

    private void buttonPresenteADActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonPresenteADActionPerformed
        try{
            int codUC = Integer.parseInt(comboCodAD.getSelectedItem().toString());
            int numTurno = Integer.parseInt(comboTurnoAD.getSelectedItem().toString());
            int idAluno = Integer.parseInt(comboAlunoAD.getSelectedItem().toString());
        
            facade.marcarFalta(codUC, numTurno, idAluno, 0);
            comboAlunoAD.removeItemAt(comboAlunoAD.getSelectedIndex());
            
        }catch(NumberFormatException e){
            ImageIcon icon = new ImageIcon(getClass().getClassLoader().getResource("resources/warning.png"));
            JOptionPane.showMessageDialog(null, "Preencha todos os campos!", "Aviso", JOptionPane.INFORMATION_MESSAGE, icon);
        }catch(NullPointerException e){
            ImageIcon icon = new ImageIcon(getClass().getClassLoader().getResource("resources/warning.png"));
            JOptionPane.showMessageDialog(null, "Já marcou todas as presenças do turno!", "Aviso", JOptionPane.INFORMATION_MESSAGE, icon);
        }
    }//GEN-LAST:event_buttonPresenteADActionPerformed

    private void buttonFaltouADActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonFaltouADActionPerformed
        try{
            int codUC = Integer.parseInt(comboCodAD.getSelectedItem().toString());
            int numTurno = Integer.parseInt(comboTurnoAD.getSelectedItem().toString());
            int idAluno = Integer.parseInt(comboAlunoAD.getSelectedItem().toString());
        
            facade.marcarFalta(codUC, numTurno, idAluno, 1);
            comboAlunoAD.removeItemAt(comboAlunoAD.getSelectedIndex());

        }catch(NumberFormatException e){
            ImageIcon icon = new ImageIcon(getClass().getClassLoader().getResource("resources/warning.png"));
            JOptionPane.showMessageDialog(null, "Preencha todos os campos!", "Aviso", JOptionPane.INFORMATION_MESSAGE, icon);
        }catch(NullPointerException e){
            ImageIcon icon = new ImageIcon(getClass().getClassLoader().getResource("resources/warning.png"));
            JOptionPane.showMessageDialog(null, "Já marcou todas as presenças do turno!", "Aviso", JOptionPane.INFORMATION_MESSAGE, icon);
        }
    }//GEN-LAST:event_buttonFaltouADActionPerformed

    private void buttonLogoutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonLogoutActionPerformed
        facade.logout(this,formPai);
    }//GEN-LAST:event_buttonLogoutActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton buttonDirCurso;
    private javax.swing.JButton buttonDirUC;
    private javax.swing.JButton buttonFaltouAD;
    private javax.swing.JButton buttonLogout;
    private javax.swing.JButton buttonPresenteAD;
    private javax.swing.JComboBox<String> comboAlunoAD;
    private javax.swing.JComboBox<String> comboCodAD;
    private javax.swing.JComboBox<String> comboTurnoAD;
    private javax.swing.JLabel jLabel34;
    private javax.swing.JLabel jLabel35;
    private javax.swing.JLabel jLabel36;
    private javax.swing.JLabel jLabel37;
    private javax.swing.JLabel jLabel38;
    private javax.swing.JPanel panelADir;
    private javax.swing.JPanel panelADoc;
    private javax.swing.JTabbedPane tabDocente;
    private javax.swing.JTextField textNumAulas;
    // End of variables declaration//GEN-END:variables
}
