package horarios.presentation;

/**
 *
 * @author Francisco Oliveira
 * @author Raul Vilas Boas
 * @author Vitor Peixoto
 */
import horarios.business.*;
import java.awt.Color;
import java.sql.SQLException;
import java.util.Collection;
import java.util.HashSet;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.DefaultListModel;
import javax.swing.JFrame;
import javax.swing.table.DefaultTableModel;

public class FormEstudante extends javax.swing.JFrame {
    private Facade facade;
    private final JFrame formPai;
    private Collection<Registo> turnos = new HashSet<>();
    private DefaultTableModel modelTable;
    private DefaultListModel<String> modelList = new DefaultListModel<>();
    
    public FormEstudante(Facade facade, JFrame formPai) {
        this.facade = facade;
        this.formPai = formPai;
        refreshTable();
        refreshList();
        initComponents();
        this.setDefaultCloseOperation(0);
        this.setLocationRelativeTo(null);
        refreshComboUC();
        refreshComboTurno();
        listPedidosTroca.setSelectedIndex(0);
        fases();
    }
    
    private void fases(){
        int fase = facade.getDocenteDAO().getFase();
        if(fase==1 || fase==3){
            tabEstudante1.setEnabledAt(0, false);
            tabEstudante1.setBackgroundAt(0, Color.gray);
            tabEstudante1.setForegroundAt(0, Color.darkGray);
            tabEstudante1.setEnabledAt(1, false);
            tabEstudante1.setBackgroundAt(1, Color.gray);
            tabEstudante1.setForegroundAt(1, Color.darkGray);
            tabEstudante1.setSelectedIndex(2);
        }
    }
    
    private void refreshComboUC() { 
        comboUCTroca.removeAllItems();
        for(Integer i : facade.getRegistoDAO().listarUCAluno(facade.getSessao().getID())) {
            comboUCTroca.addItem(Integer.toString(i));
        }
    }
    private void refreshComboTurno() {    
        int codUC = Integer.parseInt(comboUCTroca.getSelectedItem().toString());
        comboTurnoNovo.removeAllItems();
        comboTurnoTroca.removeAllItems();
        comboTurnoTroca.addItem(Integer.toString(facade.getRegistoDAO().getTurno(facade.getSessao().getID(), codUC)));
        for(Turno t : facade.getTurnoDAO().turnosDaUC(codUC)) {
            comboTurnoNovo.addItem(Integer.toString(t.getTurno()));
        }
        comboTurnoNovo.removeItem(comboTurnoTroca.getSelectedItem().toString());
    }
    private void refreshTable(){
        turnos = facade.getTurnos(facade.getSessao().getID());
        
        String[] colunas = {"UC", "Tipo", "Turno", "% Faltas", "Dia", "Hora",};
        Object[][] data = new Object[facade.getRegistoDAO().getNumTurnos(facade.getSessao().getID())][6];
        int i=0;
        for (Registo r : turnos){
            data[i][0] = r.getUC().getAbrev();
            data[i][1] = r.getTurno().getTipoAula().getTipo();
            data[i][2] = r.getTurno().getTurno();
            if(r.getAulas()==0){
                data[i][3] = 0;
            } else{
                data[i][3] = (r.getFaltas()/r.getAulas())*100;
            }
            data[i][4] = r.getTurno().getDia();
            data[i][5] = r.getTurno().getHora();
            
            i++;
        }
        modelTable = new DefaultTableModel(data,colunas);
    }
    private void refreshList(){
        modelList.clear();
        Collection<Troca> trocas = facade.verTrocas(facade.getSessao().getID());
        for(Troca t : trocas){
            if(!modelList.contains(t.getUC()) ) modelList.addElement(Integer.toString(t.getID()));
        }
    }
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        tabEstudante1 = new javax.swing.JTabbedPane();
        jPanel1 = new javax.swing.JPanel();
        comboUCTroca = new javax.swing.JComboBox<>();
        comboTurnoTroca = new javax.swing.JComboBox<>();
        comboTurnoNovo = new javax.swing.JComboBox<>();
        comboAlunoTroca = new javax.swing.JComboBox<>();
        buttonPedido = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        listPedidosTroca = new javax.swing.JList<>();
        jLabel4 = new javax.swing.JLabel();
        textTurnoAtual = new javax.swing.JTextField();
        textDiaAtual = new javax.swing.JTextField();
        textHoraAtual = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        textTurnoNovo = new javax.swing.JTextField();
        textDiaNovo = new javax.swing.JTextField();
        textHoraNovo = new javax.swing.JTextField();
        buttonTrocaAceitar = new javax.swing.JButton();
        buttonTrocaRecusar = new javax.swing.JButton();
        textUC = new javax.swing.JTextField();
        jPanel3 = new javax.swing.JPanel();
        jScrollPane3 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        buttonLogout = new javax.swing.JButton();

        jLabel1.setText("jLabel1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(255, 255, 255));

        comboUCTroca.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                comboUCTrocaActionPerformed(evt);
            }
        });

        comboTurnoNovo.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                comboTurnoNovoFocusLost(evt);
            }
        });

        buttonPedido.setText("Efetuar pedido");
        buttonPedido.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonPedidoActionPerformed(evt);
            }
        });

        jLabel6.setFont(new java.awt.Font("Lucida Grande", 0, 10)); // NOI18N
        jLabel6.setText("UC");

        jLabel7.setFont(new java.awt.Font("Lucida Grande", 0, 10)); // NOI18N
        jLabel7.setText("Atual turno");

        jLabel8.setFont(new java.awt.Font("Lucida Grande", 0, 10)); // NOI18N
        jLabel8.setText("Novo turno");

        jLabel9.setFont(new java.awt.Font("Lucida Grande", 0, 10)); // NOI18N
        jLabel9.setText("Selecione um aluno para trocar de turno");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(buttonPedido, javax.swing.GroupLayout.PREFERRED_SIZE, 149, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(129, 129, 129))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(comboUCTroca, javax.swing.GroupLayout.PREFERRED_SIZE, 122, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel6))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(comboTurnoTroca, javax.swing.GroupLayout.PREFERRED_SIZE, 121, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel7))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel8)
                            .addComponent(comboTurnoNovo, javax.swing.GroupLayout.PREFERRED_SIZE, 121, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(jLabel9)
                    .addComponent(comboAlunoTroca, javax.swing.GroupLayout.PREFERRED_SIZE, 122, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(16, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(9, 9, 9)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(jLabel7)
                    .addComponent(jLabel8))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(comboUCTroca, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(comboTurnoTroca, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(comboTurnoNovo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel9)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(comboAlunoTroca, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(27, 27, 27)
                .addComponent(buttonPedido, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(53, Short.MAX_VALUE))
        );

        tabEstudante1.addTab("Trocar de turno", jPanel1);

        listPedidosTroca.setModel(modelList);
        listPedidosTroca.addListSelectionListener(new javax.swing.event.ListSelectionListener() {
            public void valueChanged(javax.swing.event.ListSelectionEvent evt) {
                listPedidosTrocaValueChanged(evt);
            }
        });
        jScrollPane1.setViewportView(listPedidosTroca);

        jLabel4.setText("Turno atual:");

        textTurnoAtual.setText("Turno");

        textDiaAtual.setText("Dia");

        textHoraAtual.setText("Hora");

        jLabel5.setText("Turno novo:");

        textTurnoNovo.setText("Turno");

        textDiaNovo.setText("Dia");

        textHoraNovo.setText("Hora");

        buttonTrocaAceitar.setText("Aceitar");
        buttonTrocaAceitar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonTrocaAceitarActionPerformed(evt);
            }
        });

        buttonTrocaRecusar.setText("Recusar");
        buttonTrocaRecusar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonTrocaRecusarActionPerformed(evt);
            }
        });

        textUC.setEditable(false);
        textUC.setFont(new java.awt.Font("Lucida Grande", 0, 15)); // NOI18N
        textUC.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(27, 27, 27)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                                .addComponent(textTurnoAtual, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jLabel4))
                            .addComponent(textDiaAtual)
                            .addComponent(textHoraAtual)
                            .addComponent(buttonTrocaAceitar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                                .addComponent(textTurnoNovo, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jLabel5))
                            .addComponent(textDiaNovo)
                            .addComponent(textHoraNovo)
                            .addComponent(buttonTrocaRecusar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(110, 110, 110)
                        .addComponent(textUC, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(26, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(textUC, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(jLabel5)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(textTurnoNovo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(textDiaNovo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(textHoraNovo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(jLabel4)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(textTurnoAtual, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(textDiaAtual, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(textHoraAtual, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(buttonTrocaAceitar, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(buttonTrocaRecusar, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 227, Short.MAX_VALUE))
                .addContainerGap())
        );

        tabEstudante1.addTab("Pedidos de troca", jPanel2);

        jTable1.setModel(modelTable);
        jScrollPane3.setViewportView(jTable1);

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane3, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 410, Short.MAX_VALUE)
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane3, javax.swing.GroupLayout.DEFAULT_SIZE, 239, Short.MAX_VALUE)
        );

        tabEstudante1.addTab("Consultar turnos", jPanel3);

        buttonLogout.setText("Logout");
        buttonLogout.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonLogoutActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(tabEstudante1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 431, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(buttonLogout)
                .addGap(170, 170, 170))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(tabEstudante1, javax.swing.GroupLayout.PREFERRED_SIZE, 285, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(buttonLogout)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void buttonLogoutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonLogoutActionPerformed
        facade.logout(this,formPai);
    }//GEN-LAST:event_buttonLogoutActionPerformed

    private void comboUCTrocaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_comboUCTrocaActionPerformed
        refreshComboTurno();
    }//GEN-LAST:event_comboUCTrocaActionPerformed

    private void buttonPedidoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonPedidoActionPerformed
        int idAlunoRequerente = facade.getSessao().getID();
        int idAlunoRequerido  = Integer.parseInt(comboAlunoTroca.getSelectedItem().toString());
        int codUC = Integer.parseInt(comboUCTroca.getSelectedItem().toString());
        int nTurnoRequerente = Integer.parseInt(comboTurnoTroca.getSelectedItem().toString());
        int nTurnoRequerido  = Integer.parseInt(comboTurnoNovo.getSelectedItem().toString());
        Troca t = new Troca(0, idAlunoRequerente, idAlunoRequerido, codUC, nTurnoRequerente, nTurnoRequerido);
        try {
            facade.trocaTurno(t);
        } catch (SQLException | ClassNotFoundException ex) {
            Logger.getLogger(FormTrabEstudante.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_buttonPedidoActionPerformed

    private void comboTurnoNovoFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_comboTurnoNovoFocusLost
        comboAlunoTroca.removeAllItems();
        for(Integer i : facade.getRegistoDAO().alunosInscritosTurno(Integer.parseInt(comboTurnoNovo.getSelectedItem().toString()))) {
            comboAlunoTroca.addItem(Integer.toString(i));
        }
    }//GEN-LAST:event_comboTurnoNovoFocusLost

    private void listPedidosTrocaValueChanged(javax.swing.event.ListSelectionEvent evt) {//GEN-FIRST:event_listPedidosTrocaValueChanged
        Collection<Troca> trocas = facade.verTrocas(facade.getSessao().getID());
        if(!trocas.isEmpty()){ 
            Troca t = facade.getTrocaDAO().getTroca(Integer.parseInt(listPedidosTroca.getSelectedValue()));
        
            textTurnoAtual.setText("Turno "+Integer.toString(facade.getTurnoDAO().getTurno(t.getTID2()).getTurno()));
            textTurnoNovo.setText("Turno "+Integer.toString(facade.getTurnoDAO().getTurno(t.getTID1()).getTurno()));
            textDiaAtual.setText(facade.getTurnoDAO().getTurno(facade.getTrocaDAO().getTroca(Integer.parseInt(listPedidosTroca.getSelectedValue())).getTID2()).getDia());
            textDiaNovo.setText(facade.getTurnoDAO().getTurno(facade.getTrocaDAO().getTroca(Integer.parseInt(listPedidosTroca.getSelectedValue())).getTID1()).getDia());
            textHoraAtual.setText(Integer.toString(facade.getTurnoDAO().getTurno(facade.getTrocaDAO().getTroca(Integer.parseInt(listPedidosTroca.getSelectedValue())).getTID2()).getHora())+"h");
            textHoraNovo.setText(Integer.toString(facade.getTurnoDAO().getTurno(facade.getTrocaDAO().getTroca(Integer.parseInt(listPedidosTroca.getSelectedValue())).getTID1()).getHora())+"h");
            textUC.setText(facade.getTurnoDAO().getUC(t.getUC()).getAbrev());
        }
    }//GEN-LAST:event_listPedidosTrocaValueChanged

    private void buttonTrocaAceitarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonTrocaAceitarActionPerformed
        Troca t = facade.getTrocaDAO().getTroca(Integer.parseInt(listPedidosTroca.getSelectedValue()));
        try {
            facade.aceitarTroca(t);
        } catch (SQLException | ClassNotFoundException ex) {
            Logger.getLogger(FormTrabEstudante.class.getName()).log(Level.SEVERE, null, ex);
        }
        refreshList();
        listPedidosTroca.setModel(modelList);
        refreshTable();
        refreshComboTurno();
        jTable1.setModel(modelTable);
        textTurnoAtual.setText("");
        textTurnoNovo.setText("");
        textDiaAtual.setText("");
        textDiaNovo.setText("");
        textHoraAtual.setText("");
        textHoraNovo.setText("");
        textUC.setText("");
    }//GEN-LAST:event_buttonTrocaAceitarActionPerformed

    private void buttonTrocaRecusarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonTrocaRecusarActionPerformed
        Troca t = facade.getTrocaDAO().getTroca(Integer.parseInt(listPedidosTroca.getSelectedValue()));
        try {
            facade.recusarTroca(t);
        } catch (SQLException | ClassNotFoundException ex) {
            Logger.getLogger(FormTrabEstudante.class.getName()).log(Level.SEVERE, null, ex);
        }
        refreshList();
        listPedidosTroca.setModel(modelList);
        textTurnoAtual.setText("");
        textTurnoNovo.setText("");
        textDiaAtual.setText("");
        textDiaNovo.setText("");
        textHoraAtual.setText("");
        textHoraNovo.setText("");
        textUC.setText("");
    }//GEN-LAST:event_buttonTrocaRecusarActionPerformed

    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton buttonLogout;
    private javax.swing.JButton buttonPedido;
    private javax.swing.JButton buttonTrocaAceitar;
    private javax.swing.JButton buttonTrocaRecusar;
    private javax.swing.JComboBox<String> comboAlunoTroca;
    private javax.swing.JComboBox<String> comboTurnoNovo;
    private javax.swing.JComboBox<String> comboTurnoTroca;
    private javax.swing.JComboBox<String> comboUCTroca;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JTable jTable1;
    private javax.swing.JList<String> listPedidosTroca;
    private javax.swing.JTabbedPane tabEstudante1;
    private javax.swing.JTextField textDiaAtual;
    private javax.swing.JTextField textDiaNovo;
    private javax.swing.JTextField textHoraAtual;
    private javax.swing.JTextField textHoraNovo;
    private javax.swing.JTextField textTurnoAtual;
    private javax.swing.JTextField textTurnoNovo;
    private javax.swing.JTextField textUC;
    // End of variables declaration//GEN-END:variables
}
