package horarios.presentation;

/**
 *
 * @author Francisco Oliveira
 * @author Raul Vilas Boas
 * @author Vitor Peixoto
 */
import horarios.business.*;
import java.awt.Color;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.ImageIcon;
import javax.swing.JFrame;
import javax.swing.JOptionPane;


public class FormDirecaoUC extends javax.swing.JFrame {
    private Facade facade;
    private final JFrame formPai;
    
    public FormDirecaoUC(Facade facade, JFrame formPai) {
        initComponents();
        this.facade = facade;
        this.formPai = formPai;
        this.setLocationRelativeTo(null);
        this.setDefaultCloseOperation(DISPOSE_ON_CLOSE);
        refreshComboAluno();
        refreshComboUC();
        fases();
    }
    
    private void fases(){
        int fase = facade.getDocenteDAO().getFase();
        if(fase==1){
            tabDirUC.setEnabledAt(0, false);
            tabDirUC.setBackgroundAt(0, Color.gray);
            tabDirUC.setForegroundAt(0, Color.darkGray);
            tabDirUC.setEnabledAt(2, false);
            tabDirUC.setBackgroundAt(2, Color.gray);
            tabDirUC.setForegroundAt(2, Color.darkGray);
            tabDirUC.setSelectedIndex(1);

        }
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        tabDirUC = new javax.swing.JTabbedPane();
        panelAA = new javax.swing.JPanel();
        comboIDAlunoAA = new javax.swing.JComboBox<>();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        comboCodAA = new javax.swing.JComboBox<>();
        jLabel17 = new javax.swing.JLabel();
        comboTurnoAA = new javax.swing.JComboBox<>();
        buttonAA = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        comboTurno = new javax.swing.JComboBox<>();
        comboUC = new javax.swing.JComboBox<>();
        jLabel18 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        buttonCap = new javax.swing.JButton();
        textCap = new javax.swing.JTextField();
        jLabel20 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        comboIDAlunoAA1 = new javax.swing.JComboBox<>();
        jLabel21 = new javax.swing.JLabel();
        jLabel22 = new javax.swing.JLabel();
        comboCodAA2 = new javax.swing.JComboBox<>();
        comboTurnoAA2 = new javax.swing.JComboBox<>();
        jLabel23 = new javax.swing.JLabel();
        comboIDAlunoAA2 = new javax.swing.JComboBox<>();
        comboTurnoAA3 = new javax.swing.JComboBox<>();
        jLabel24 = new javax.swing.JLabel();
        jLabel26 = new javax.swing.JLabel();
        buttonTrocar = new javax.swing.JButton();
        buttonRemover = new javax.swing.JButton();
        jSeparator1 = new javax.swing.JSeparator();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel15.setFont(new java.awt.Font("Lucida Grande", 0, 10)); // NOI18N
        jLabel15.setText("ID Aluno");

        jLabel16.setFont(new java.awt.Font("Lucida Grande", 0, 10)); // NOI18N
        jLabel16.setText("Código UC");

        comboCodAA.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                comboCodAAActionPerformed(evt);
            }
        });

        jLabel17.setFont(new java.awt.Font("Lucida Grande", 0, 10)); // NOI18N
        jLabel17.setText("Turno ");

        buttonAA.setText("Alocar");
        buttonAA.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonAAActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout panelAALayout = new javax.swing.GroupLayout(panelAA);
        panelAA.setLayout(panelAALayout);
        panelAALayout.setHorizontalGroup(
            panelAALayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelAALayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelAALayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel15)
                    .addComponent(comboIDAlunoAA, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(panelAALayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel16)
                    .addComponent(comboCodAA, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(buttonAA, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(panelAALayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel17)
                    .addComponent(comboTurnoAA, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        panelAALayout.setVerticalGroup(
            panelAALayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelAALayout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addGroup(panelAALayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(panelAALayout.createSequentialGroup()
                        .addComponent(jLabel17)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(comboTurnoAA, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(panelAALayout.createSequentialGroup()
                        .addComponent(jLabel16, javax.swing.GroupLayout.PREFERRED_SIZE, 13, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(comboCodAA, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(panelAALayout.createSequentialGroup()
                        .addComponent(jLabel15)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(comboIDAlunoAA, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 47, Short.MAX_VALUE)
                .addComponent(buttonAA)
                .addGap(16, 16, 16))
        );

        tabDirUC.addTab("Alocar aluno", panelAA);

        comboUC.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                comboUCActionPerformed(evt);
            }
        });

        jLabel18.setFont(new java.awt.Font("Lucida Grande", 0, 10)); // NOI18N
        jLabel18.setText("Código UC");

        jLabel19.setFont(new java.awt.Font("Lucida Grande", 0, 10)); // NOI18N
        jLabel19.setText("Turno ");

        buttonCap.setText("Definir capacidade");
        buttonCap.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonCapActionPerformed(evt);
            }
        });

        jLabel20.setFont(new java.awt.Font("Lucida Grande", 0, 10)); // NOI18N
        jLabel20.setText("Capacidade");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel18)
                            .addComponent(comboUC, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(comboTurno, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel19))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel20)
                            .addComponent(textCap, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(130, 130, 130)
                        .addComponent(buttonCap)))
                .addContainerGap(34, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel19)
                            .addComponent(jLabel20))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(comboTurno, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(textCap, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel18, javax.swing.GroupLayout.PREFERRED_SIZE, 13, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(comboUC, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 45, Short.MAX_VALUE)
                .addComponent(buttonCap)
                .addGap(16, 16, 16))
        );

        tabDirUC.addTab("Capacidade", jPanel1);

        comboIDAlunoAA1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                comboIDAlunoAA1ActionPerformed(evt);
            }
        });

        jLabel21.setFont(new java.awt.Font("Lucida Grande", 0, 10)); // NOI18N
        jLabel21.setText("ID Aluno");

        jLabel22.setFont(new java.awt.Font("Lucida Grande", 0, 10)); // NOI18N
        jLabel22.setText("Código UC");

        comboCodAA2.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                comboCodAA2FocusLost(evt);
            }
        });

        jLabel23.setFont(new java.awt.Font("Lucida Grande", 0, 10)); // NOI18N
        jLabel23.setText("Turno ");

        comboIDAlunoAA2.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                comboIDAlunoAA2FocusLost(evt);
            }
        });

        jLabel24.setFont(new java.awt.Font("Lucida Grande", 0, 10)); // NOI18N
        jLabel24.setText("Turno ");

        jLabel26.setFont(new java.awt.Font("Lucida Grande", 0, 10)); // NOI18N
        jLabel26.setText("ID Aluno");

        buttonTrocar.setText("Trocar turnos");
        buttonTrocar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonTrocarActionPerformed(evt);
            }
        });

        buttonRemover.setText("Remover");
        buttonRemover.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonRemoverActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jSeparator1)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel26)
                        .addGap(176, 176, 176)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(comboTurnoAA3, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(buttonTrocar, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jLabel24)))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(jLabel21)
                                .addGap(85, 85, 85)
                                .addComponent(jLabel22))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(comboIDAlunoAA1, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(comboCodAA2, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel2Layout.createSequentialGroup()
                                        .addComponent(comboTurnoAA2, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(buttonRemover, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addComponent(jLabel23)))
                            .addComponent(comboIDAlunoAA2, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 1, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel21)
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel23)
                        .addComponent(jLabel22, javax.swing.GroupLayout.PREFERRED_SIZE, 13, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(comboIDAlunoAA1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(comboCodAA2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(comboTurnoAA2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(buttonRemover))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel26)
                    .addComponent(jLabel24))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(comboIDAlunoAA2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(comboTurnoAA3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(buttonTrocar))
                .addContainerGap(14, Short.MAX_VALUE))
        );

        tabDirUC.addTab("Trocar alunos", jPanel2);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(tabDirUC, javax.swing.GroupLayout.Alignment.TRAILING)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(tabDirUC, javax.swing.GroupLayout.PREFERRED_SIZE, 199, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void refreshComboAluno() { 
        for(Aluno a : facade.getAlunoDAO().values()) {
            comboIDAlunoAA.addItem(Integer.toString(a.getID()));
            comboIDAlunoAA1.addItem(Integer.toString(a.getID()));
        }
    }
    private void refreshComboUC() { 
        for(UC c : facade.getUCDAO().values()) {
            comboUC.addItem(Integer.toString(c.getUC()));
            comboCodAA.addItem(Integer.toString(c.getUC()));
        }
    }

    private void comboCodAAActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_comboCodAAActionPerformed
        int codUC = Integer.parseInt(comboCodAA.getSelectedItem().toString());
        comboTurnoAA.removeAllItems();
        for(Turno t : facade.getTurnoDAO().turnosDaUC(codUC)) {
            comboTurnoAA.addItem(Integer.toString(t.getTurno()));
        }
    }//GEN-LAST:event_comboCodAAActionPerformed

    private void buttonAAActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonAAActionPerformed
        try{
            int idAluno = Integer.parseInt(comboIDAlunoAA.getSelectedItem().toString());
            int codigoUC = Integer.parseInt(comboCodAA.getSelectedItem().toString());
            int numeroTurno = Integer.parseInt(comboTurnoAA.getSelectedItem().toString());
            
            facade.alocarAluno(idAluno, codigoUC, numeroTurno);
        }catch(NumberFormatException e){
            ImageIcon icon = new ImageIcon(getClass().getClassLoader().getResource("resources/warning.png"));
            JOptionPane.showMessageDialog(null, "Preencha todos os campos!", "Aviso", JOptionPane.INFORMATION_MESSAGE, icon);
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(FormDirecaoCurso.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_buttonAAActionPerformed

    private void comboUCActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_comboUCActionPerformed
        int codUC = Integer.parseInt(comboUC.getSelectedItem().toString());
        comboTurno.removeAllItems();
        for(Turno t : facade.getTurnoDAO().turnosDaUC(codUC)) {
            comboTurno.addItem(Integer.toString(t.getTurno()));
        }
    }//GEN-LAST:event_comboUCActionPerformed

    private void buttonCapActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonCapActionPerformed
        int numTurno = Integer.parseInt(comboTurno.getSelectedItem().toString());
        int cap = Integer.parseInt(textCap.getText());
        int idTipo = facade.getTurnoDAO().getTurno(numTurno).getTipoAula().getID();
        
        facade.alteraCapacidade(numTurno, cap, idTipo);
    }//GEN-LAST:event_buttonCapActionPerformed

    private void comboIDAlunoAA1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_comboIDAlunoAA1ActionPerformed
        comboCodAA2.removeAllItems();
        for(Integer i : facade.getRegistoDAO().listarUCAluno(Integer.parseInt(comboIDAlunoAA1.getSelectedItem().toString()))) {
            comboCodAA2.addItem(i.toString());

        }
    }//GEN-LAST:event_comboIDAlunoAA1ActionPerformed

    private void comboCodAA2FocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_comboCodAA2FocusLost
        comboIDAlunoAA2.removeAllItems();
        for(Integer i : facade.getRegistoDAO().alunosInscritosUC(Integer.parseInt(comboCodAA2.getSelectedItem().toString()))) {
            comboIDAlunoAA2.addItem(i.toString());
        }
        
        comboTurnoAA3.removeAllItems();
        for(Turno t : facade.getTurnoDAO().turnosDaUC(Integer.parseInt(comboCodAA2.getSelectedItem().toString()))) {
            comboTurnoAA3.addItem(Integer.toString(t.getTurno()));
        }
        
        comboTurnoAA2.removeAllItems();
        int idAluno = Integer.parseInt(comboIDAlunoAA1.getSelectedItem().toString());
        int codUC = Integer.parseInt(comboCodAA2.getSelectedItem().toString());
        int numTurno = facade.getRegistoDAO().getTurno(idAluno, codUC);
        comboTurnoAA2.addItem(Integer.toString(numTurno)); 
    }//GEN-LAST:event_comboCodAA2FocusLost

    private void comboIDAlunoAA2FocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_comboIDAlunoAA2FocusLost
        comboTurnoAA3.removeAllItems();
        int idAluno = Integer.parseInt(comboIDAlunoAA2.getSelectedItem().toString());
        int codUC = Integer.parseInt(comboCodAA2.getSelectedItem().toString());
        int numTurno = facade.getRegistoDAO().getTurno(idAluno, codUC);
        comboTurnoAA3.addItem(Integer.toString(numTurno)); 
    }//GEN-LAST:event_comboIDAlunoAA2FocusLost

    private void buttonTrocarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonTrocarActionPerformed
        int aluno1 = Integer.parseInt(comboIDAlunoAA1.getSelectedItem().toString());
        int aluno2 = Integer.parseInt(comboIDAlunoAA2.getSelectedItem().toString());
        int codUC = Integer.parseInt(comboCodAA2.getSelectedItem().toString());
        int turno1 = Integer.parseInt(comboTurnoAA2.getSelectedItem().toString());
        int turno2 = Integer.parseInt(comboTurnoAA3.getSelectedItem().toString());        
        Troca t = new Troca(0, aluno1, aluno2, codUC, turno1, turno2);
        try {
            facade.trocaTurnoDiretor(t);
        } catch (SQLException | ClassNotFoundException ex) {
            Logger.getLogger(FormDirecaoUC.class.getName()).log(Level.SEVERE, null, ex);
        }
        this.refreshComboAluno();
        this.refreshComboUC();
    }//GEN-LAST:event_buttonTrocarActionPerformed

    private void buttonRemoverActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonRemoverActionPerformed
        try {
            facade.removeAluno(Integer.parseInt(comboIDAlunoAA1.getSelectedItem().toString()), Integer.parseInt(comboTurnoAA2.getSelectedItem().toString()));
        } catch (ClassNotFoundException | NumberFormatException | SQLException ex) {
            Logger.getLogger(FormDirecaoUC.class.getName()).log(Level.SEVERE, null, ex); }
        comboIDAlunoAA1.removeItemAt(comboIDAlunoAA1.getSelectedIndex());

    }//GEN-LAST:event_buttonRemoverActionPerformed
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton buttonAA;
    private javax.swing.JButton buttonCap;
    private javax.swing.JButton buttonRemover;
    private javax.swing.JButton buttonTrocar;
    private javax.swing.JComboBox<String> comboCodAA;
    private javax.swing.JComboBox<String> comboCodAA2;
    private javax.swing.JComboBox<String> comboIDAlunoAA;
    private javax.swing.JComboBox<String> comboIDAlunoAA1;
    private javax.swing.JComboBox<String> comboIDAlunoAA2;
    private javax.swing.JComboBox<String> comboTurno;
    private javax.swing.JComboBox<String> comboTurnoAA;
    private javax.swing.JComboBox<String> comboTurnoAA2;
    private javax.swing.JComboBox<String> comboTurnoAA3;
    private javax.swing.JComboBox<String> comboUC;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JPanel panelAA;
    private javax.swing.JTabbedPane tabDirUC;
    private javax.swing.JTextField textCap;
    // End of variables declaration//GEN-END:variables
}
